import React from "react";
import {
  Leaf,
  Coffee,
  Fuel,
  Hospital as HospitalIcon,
  Utensils,
  Pill,
  Landmark,
  Dumbbell,
  Wine,
  Shuffle,
  UtensilsCrossed,
  Gem,
  Binoculars,
  Cake,
  Trees,
  BookOpen,
  Waves,
  Library,
  Sunset,
  Mountain,
  Store,
  CreditCard,
  Beer,
  Disc,
  Gamepad2,
  Trophy,
  Compass,
  Heart,
  Shield,
  Users
} from "lucide-react";

// Real Mapbox Search Box API canonical category IDs.
// Reference: https://docs.mapbox.com/api/search/search-box/#category-search
// We pass these to /search/searchbox/v1/category/{canonical_id}.

export const CATEGORIES = [
  {
    key: "grass",
    label: "Grass",
    searchCanonical: "park",
    searchAlternatives: ["nature_preserve", "garden", "sports_field"],
    accent: "#22c55e",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #052e1688 0%, #0a0a0a 70%)",
    iconKey: "grass",
    hero: true,
    glow: "#16a34a",
    Icon: Leaf,
  },
  {
    key: "cafe",
    label: "Café",
    searchCanonical: "coffee_shop",
    searchAlternatives: ["cafe", "coffee", "bakery"],
    accent: "#f97316",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #2c120788 0%, #0a0a0a 70%)",
    iconKey: "coffee",
    glow: "#ea580c",
    Icon: Coffee,
  },
  {
    key: "hospital",
    label: "Hospital",
    searchCanonical: "hospital",
    searchAlternatives: ["clinic", "medical_care", "dentist"],
    accent: "#ef4444",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #2d0a0a88 0%, #0a0a0a 70%)",
    iconKey: "hospital",
    glow: "#dc2626",
    Icon: HospitalIcon,
  },
  {
    key: "pharmacy",
    label: "Pharmacy",
    searchCanonical: "pharmacy",
    searchAlternatives: ["drugstore"],
    accent: "#10b981",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #02291888 0%, #0a0a0a 70%)",
    iconKey: "pill",
    glow: "#059669",
    Icon: Pill,
  },
  {
    key: "atm",
    label: "ATM",
    searchCanonical: "atm",
    searchAlternatives: ["bank"],
    accent: "#3b82f6",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #0a162888 0%, #0a0a0a 70%)",
    iconKey: "landmark",
    glow: "#2563eb",
    Icon: CreditCard,
  },
  {
    key: "gym",
    label: "Gym",
    searchCanonical: "gym",
    searchAlternatives: ["fitness_center", "sports_club", "swimming_pool", "sports_field"],
    accent: "#a855f7",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #1a0a2e88 0%, #0a0a0a 70%)",
    iconKey: "dumbbell",
    glow: "#9333ea",
    Icon: Dumbbell,
  },
  {
    key: "bar",
    label: "Bar",
    searchCanonical: "bar",
    searchAlternatives: ["pub", "lounge"],
    accent: "#f59e0b",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #1c150088 0%, #0a0a0a 70%)",
    iconKey: "wine",
    glow: "#d97706",
    Icon: Beer,
  },
  {
    key: "fuel",
    label: "Fuel",
    searchCanonical: "gas_station",
    searchAlternatives: ["fuel", "ev_charging"],
    accent: "#eab308",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #1c150088 0%, #0a0a0a 70%)",
    iconKey: "fuel",
    glow: "#ca8a04",
    Icon: Fuel,
  },
  {
    key: "street_food",
    label: "Street Food",
    searchCanonical: "restaurant",
    searchAlternatives: ["food", "cafe", "fast_food", "bakery", "deli"],
    accent: "#fb923c",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #2c100588 0%, #0a0a0a 70%)",
    iconKey: "utensils",
    glow: "#f97316",
    Icon: UtensilsCrossed,
  },
  {
    key: "hidden_gems",
    label: "Hidden Gems",
    searchCanonical: "tourist_attraction",
    searchAlternatives: ["museum", "historic", "monument", "artwork", "viewpoint"],
    accent: "#a78bfa",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #1c0a2e88 0%, #0a0a0a 70%)",
    iconKey: "gem",
    glow: "#8b5cf6",
    Icon: Gem,
  },
  {
    key: "landmark",
    label: "Landmark",
    searchCanonical: "tourist_attraction",
    searchAlternatives: ["monument", "historic_site", "museum", "castle"],
    searchQuery: "Taj Mahal",
    searchQueryCategory: "tourist_attraction",
    accent: "#f59e0b",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #1c150088 0%, #0a0a0a 70%)",
    iconKey: "landmark",
    glow: "#d97706",
    Icon: Landmark,
  },
  {
    key: "viewpoint",
    label: "Viewpoint",
    searchCanonical: "viewpoint",
    searchAlternatives: ["tourist_attraction", "scenic_lookout", "lighthouse", "monument"],
    accent: "#06b6d4",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #001c2488 0%, #0a0a0a 70%)",
    iconKey: "eye",
    glow: "#0891b2",
    Icon: Binoculars,
  },
  {
    key: "dessert",
    label: "Dessert",
    searchCanonical: "bakery",
    searchAlternatives: ["cafe", "coffee_shop", "restaurant", "food"],
    accent: "#ec4899",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #2e081888 0%, #0a0a0a 70%)",
    iconKey: "cookie",
    glow: "#db2777",
    Icon: Cake,
  },
  {
    key: "scenic_spot",
    label: "Scenic Spot",
    searchCanonical: "viewpoint",
    searchAlternatives: ["tourist_attraction", "park", "garden", "beach"],
    accent: "#10b981",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #02291888 0%, #0a0a0a 70%)",
    iconKey: "trees",
    glow: "#059669",
    Icon: Trees,
  },
  {
    key: "bookstore",
    label: "Bookstore",
    searchCanonical: "bookstore",
    searchAlternatives: ["library", "shop"],
    accent: "#f59e0b",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #1c150088 0%, #0a0a0a 70%)",
    iconKey: "book",
    glow: "#d97706",
    Icon: BookOpen,
  },
  {
    key: "fine_dining",
    label: "Fine Dining",
    searchCanonical: "restaurant",
    searchAlternatives: ["food", "cafe"],
    accent: "#f43f5e",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #2e080a88 0%, #0a0a0a 70%)",
    iconKey: "utensils",
    glow: "#e11d48",
    Icon: Utensils,
  },
  {
    key: "waterfront",
    label: "Waterfront",
    searchCanonical: "beach",
    searchAlternatives: ["marina", "port", "lake", "river", "water", "swimming_pool", "dock"],
    accent: "#06b6d4",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #001c2488 0%, #0a0a0a 70%)",
    iconKey: "waves",
    glow: "#0891b2",
    Icon: Waves,
  },
  {
    key: "quiet_place",
    label: "Quiet Place",
    searchCanonical: "library",
    searchAlternatives: ["bookstore", "museum", "place_of_worship", "church", "temple"],
    accent: "#a78bfa",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #1c0a2e88 0%, #0a0a0a 70%)",
    iconKey: "library",
    glow: "#8b5cf6",
    Icon: Library,
  },
  {
    key: "nature_spot",
    label: "Nature Spot",
    searchCanonical: "nature_preserve",
    searchAlternatives: ["park", "garden", "forest", "campground", "picnic_site"],
    accent: "#10b981",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #02291888 0%, #0a0a0a 70%)",
    iconKey: "trees",
    glow: "#059669",
    Icon: Trees,
  },
  {
    key: "sunset_point",
    label: "Sunset Point",
    searchCanonical: "viewpoint",
    searchAlternatives: ["scenic_lookout", "hill", "mountain", "peak", "beach"],
    accent: "#f43f5e",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #2e080a88 0%, #0a0a0a 70%)",
    iconKey: "sunset",
    glow: "#e11d48",
    Icon: Sunset,
  },
  {
    key: "trail",
    label: "Trail",
    searchCanonical: "trailhead",
    searchAlternatives: ["hiking_trail", "park", "nature_preserve", "climbing"],
    accent: "#84cc16",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #14280588 0%, #0a0a0a 70%)",
    iconKey: "mountain",
    glow: "#65a30d",
    Icon: Mountain,
  },
  {
    key: "convenience_store",
    label: "Convenience Store",
    searchCanonical: "convenience_store",
    searchAlternatives: ["grocery", "supermarket", "shop"],
    accent: "#3b82f6",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #0a162888 0%, #0a0a0a 70%)",
    iconKey: "store",
    glow: "#2563eb",
    Icon: Store,
  },
  {
    key: "club",
    label: "Club",
    searchCanonical: "nightclub",
    searchAlternatives: ["bar", "pub", "lounge"],
    accent: "#d946ef",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #2c053588 0%, #0a0a0a 70%)",
    iconKey: "music",
    glow: "#c026d3",
    Icon: Disc,
  },
  {
    key: "gaming_cafe",
    label: "Gaming Café",
    searchCanonical: "internet_cafe",
    searchAlternatives: ["cafe", "amusement_center", "toy_store", "electronics_store"],
    accent: "#06b6d4",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #001c2488 0%, #0a0a0a 70%)",
    iconKey: "gamepad",
    glow: "#0891b2",
    Icon: Gamepad2,
  },
  {
    key: "turf",
    label: "Turf",
    searchCanonical: "sports_field",
    searchAlternatives: ["sports_center", "stadium", "playground", "recreation_ground"],
    accent: "#22c55e",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #052e1688 0%, #0a0a0a 70%)",
    iconKey: "activity",
    glow: "#16a34a",
    Icon: Trophy,
  },
  {
    key: "random",
    label: "Random",
    searchCanonical: null,
    searchAlternatives: [],
    accent: "#94a3b8",
    accentSoft: "radial-gradient(ellipse at 60% 30%, #0f172a88 0%, #0a0a0a 70%)",
    iconKey: "shuffle",
    glow: "#64748b",
    Icon: Shuffle,
  },
];

export const MODES = {
  explore: {
    label: "Explore",
    icon: Compass,
    color: "emerald",
    mainKey: "grass",
    gridKeys: ["hidden_gems", "viewpoint", "street_food", "landmark"]
  },
  date: {
    label: "Date",
    icon: Heart,
    color: "rose",
    mainKey: "cafe",
    gridKeys: ["scenic_spot", "dessert", "fine_dining", "bookstore"]
  },
  escape: {
    label: "Escape",
    icon: Trees,
    color: "cyan",
    mainKey: "waterfront",
    gridKeys: ["nature_spot", "quiet_place", "trail", "sunset_point"]
  },
  social: {
    label: "Social",
    icon: Users,
    color: "violet",
    mainKey: "gym",
    gridKeys: ["turf", "gaming_cafe", "club", "bar"]
  },
  essentials: {
    label: "Essentials",
    icon: Shield,
    color: "amber",
    mainKey: "fuel",
    gridKeys: ["atm", "convenience_store", "hospital", "pharmacy"]
  }
};

export const getCategoryByKey = (key) =>
  CATEGORIES.find((c) => c.key === key) || null;

// The pool from which Random picks (everything except Random itself).
export const RANDOM_POOL = CATEGORIES.filter((c) => c.key !== "random");
